apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: simple-flask-app
  labels:
    app: simple-flask-app
spec:
  source:
    type: Git
    git:
      uri: https://github.com/ddjain/simple-flask-openshift-app.git
      ref: main
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: simple-flask-app:latest
  triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: flask-app-webhook-secret
