apiVersion: v1
kind: Service
metadata:
  name: simple-flask-app
  labels:
    app: simple-flask-app
spec:
  selector:
    app: simple-flask-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
